version = 0.1

[default.deploy.parameters]
stack_name = "LLMChatLangGraph"
resolve_s3 = true
s3_prefix = "LLMChatLangGraph"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "GeminiModel=gemini-3.1-flash-lite-preview OpenaiModel=gpt-5.4-nano"

[default.global.parameters]
region = "us-east-1"
